// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWQWIgcyDgy7uDozcXCpl9CpTH19FWazA',
    appId: '1:1047426911286:web:875d7559a5e65882009c97',
    messagingSenderId: '1047426911286',
    projectId: 'chess-f1a41',
    authDomain: 'chess-f1a41.firebaseapp.com',
    storageBucket: 'chess-f1a41.firebasestorage.app',
    measurementId: 'G-4YBGPW7G97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwnKYUZXpzoZTo0jYWbO7fDO_7wkmBs8Q',
    appId: '1:1047426911286:android:a0054c55fda64121009c97',
    messagingSenderId: '1047426911286',
    projectId: 'chess-f1a41',
    storageBucket: 'chess-f1a41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbmv3NnFDhyNYhmg6chqEuHE_GLLhJsI0',
    appId: '1:1047426911286:ios:b60194329e6c9d3e009c97',
    messagingSenderId: '1047426911286',
    projectId: 'chess-f1a41',
    storageBucket: 'chess-f1a41.firebasestorage.app',
    iosBundleId: 'com.example.chessCopy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWQWIgcyDgy7uDozcXCpl9CpTH19FWazA',
    appId: '1:1047426911286:web:6a2a1fae7337597d009c97',
    messagingSenderId: '1047426911286',
    projectId: 'chess-f1a41',
    authDomain: 'chess-f1a41.firebaseapp.com',
    storageBucket: 'chess-f1a41.firebasestorage.app',
    measurementId: 'G-77MTVWPV52',
  );
}
